apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: mlops-demo
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
        verbosity: detailed
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: mlops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel
        image: otel/opentelemetry-collector-contrib:0.109.0
        args: ["--config=/etc/otelcol/otel-collector-config.yaml"]
        volumeMounts:
        - name: cfg
          mountPath: /etc/otelcol
      volumes:
      - name: cfg
        configMap:
          name: otel-collector-config
